# 1.7 Introduction to Numpy 

In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
# change 3 to 10
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimentional arrays

In [9]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [12]:
n[0]

array([ 1, 20,  3])

In [13]:
n[2]

array([7, 8, 9])

In [14]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [15]:
n[:, 1]

array([20,  5,  1])

In [16]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [17]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [18]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [19]:
# randn from normal distribution

np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [20]:
np.random.seed(2)
100* np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [21]:
# randint must be an integer

np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a + 1

array([1, 2, 3, 4, 5])

In [24]:
a * 2

array([0, 2, 4, 6, 8])

In [25]:
(10 + (a*2)) ** 2

array([100, 144, 196, 256, 324])

In [26]:
b = (10 + (a*2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [27]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [28]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison Operations

In [29]:
a

array([0, 1, 2, 3, 4])

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a > b

array([False, False,  True,  True,  True])

In [33]:
a[a > b]

array([2, 3, 4])

## Summarising Operations

In [34]:
a.min()

np.int64(0)

In [35]:
b.max()

np.float64(3.24)

In [36]:
n.sum()

np.int64(35)

In [37]:
a.mean()

np.float64(2.0)

In [38]:
b.std()

np.float64(0.7947829892492667)