# 1.7 Introduction to Numpy 

In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
# change 3 to 10
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimentional arrays

In [9]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [12]:
n[0]

array([ 1, 20,  3])

In [13]:
n[2]

array([7, 8, 9])

In [14]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [15]:
n[:, 1]

array([20,  5,  1])

In [16]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [17]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [18]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [19]:
# randn from normal distribution

np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [20]:
np.random.seed(2)
100* np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [21]:
# randint must be an integer

np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a + 1

array([1, 2, 3, 4, 5])

In [24]:
a * 2

array([0, 2, 4, 6, 8])

In [25]:
(10 + (a*2)) ** 2

array([100, 144, 196, 256, 324])

In [26]:
b = (10 + (a*2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [27]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [28]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison Operations

In [29]:
a

array([0, 1, 2, 3, 4])

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a > b

array([False, False,  True,  True,  True])

In [33]:
a[a > b]

array([2, 3, 4])

## Summarising Operations

In [34]:
a.min()

np.int64(0)

In [35]:
b.max()

np.float64(3.24)

In [36]:
n.sum()

np.int64(35)

In [37]:
a.mean()

np.float64(2.0)

In [38]:
b.std()

np.float64(0.7947829892492667)

## Multiplication

In [39]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [40]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [41]:
u.shape[0]

4

In [42]:
v.shape[0]

4

In [43]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result
    

In [44]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [45]:
# vector multiplication

u.dot(v)

np.int64(14)

In [46]:
U =  np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [50]:
U.shape

(3, 4)

In [54]:
v = np.array([1, 0.5, 2, 1])
v

array([1. , 0.5, 2. , 1. ])

In [55]:
v.shape

(4,)

In [59]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v) 

    return result
    

In [60]:
matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

In [61]:
U.dot(v)

array([20. ,  6. ,  8.5])

## Matrix Matrix Multiplication 

In [64]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [65]:
def matrx_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [66]:
matrx_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [67]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [68]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [69]:
I = np.eye(3)

In [71]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [70]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [72]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [73]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [75]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 1.8 Introduction to Pandas